server:
  port: 80

#日志级别
#logging:
#  level:
#    root=info
spring:
  application:
    name: web-ui
  thymeleaf:
    cache: false # 关闭thymeleaf的缓存(热部署)
    mode: LEGACYHTML5 # 松校验
#    prefix: /templates/
#    suffix: .html
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.207.103:3306/hourse?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/hourse?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
#    password: root

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  mvc:
    static-path-pattern: /static/**
